os: linux

language: python

python:
  - "2.7"

branches:
  only:
    - master

sudo: required

install:
  - sudo apt-get install nasm
  - pip install pyasmjit
  - pip install z3-solver
  - pip install nose
  - pip install .

script: nosetests
